spring.profiles.active: atlas
spring.data.rest.base-path: /api
management.security.enabled: false

---
spring:
  profiles: local
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true

---
spring:
  profiles: atlas
  data:
    mongodb:
      #uri: mongodb://mongod3.eastus.cloudapp.azure.com:27000,mongod2.eastus.cloudapp.azure.com:27000,mongod1.eastus.cloudapp.azure.com:27000/test?ssl=false&replicaSet=rs1
      uri: mongodb://127.0.0.1:27017
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true